apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge
spec:
  tls:
    - hosts:
      - minikubeme
      secretName: tls-certificate
  rules:
    http:
      paths:
      - path: /oauth
        pathType: Prefix
        backend:
          service:
            name: auth-server
            port:
              number: 80


      - path: /product-composite
        pathType: Prefix
        backend:
          service:
            name: product-composite
            port:
              number: 80


      - path: /actuator/health
        pathType: Prefix
        backend:
          service:
            name: product-composite
            port:
              number: 80